spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

server:
  port: 8080

logging:
  level:
    com.freight.contract: DEBUG
    org.springframework.graphql: DEBUG